package com.datarain.pdp.infrastructure.audit;

public enum BusinessEventType {
    EXTRACTION_REQUESTED,
    MODERATION_CASE_CREATED,
    MODERATION_CASE_APPROVED,
    MODERATION_CASE_REJECTED,
    MODERATION_CASE_AUTO_BLOCKED,
    USER_MESSAGE_CREATED,
    USER_MESSAGE_UPDATED,
    USER_MESSAGE_DELETED,
    USER_MESSAGE_PROCESSED,
    SIGNAL_ENGINE_EXECUTED,
    SIGNAL_NORMALIZATION_EXECUTED,
    INSIGHTS_VIEWED,
    ADMIN_SYSTEM_OVERVIEW_VIEWED,
    TEST_DATA_SEEDED
}
