package com.datarain.pdp.infrastructure.audit;

public enum BusinessEventType {
    EXTRACTION_REQUESTED,
    USER_MESSAGE_CREATED,
    USER_MESSAGE_UPDATED,
    USER_MESSAGE_DELETED,
    USER_MESSAGE_PROCESSED,
    SIGNAL_ENGINE_EXECUTED,
    SIGNAL_NORMALIZATION_EXECUTED,
    INSIGHTS_VIEWED,
    ADMIN_SYSTEM_OVERVIEW_VIEWED,
    TEST_DATA_SEEDED
}
