package com.datarain.pdp.infrastructure.security.audit;

/**
 * اضافه شد: انواع رویدادهای امنیتی که لاگ میشن
 */
public enum SecurityEventType {
    LOGIN_SUCCESS,
    LOGIN_FAILED,
    LOGOUT,
    LOGOUT_ALL_DEVICES,
    TOKEN_REFRESH,
    TOKEN_REVOKED,
    ACCOUNT_LOCKED,
    ACCOUNT_UNLOCKED,
    ACCOUNT_ENABLED,
    ACCOUNT_DISABLED,
    REGISTER,
    PASSWORD_RESET_REQUESTED,
    PASSWORD_RESET_COMPLETED,
    EMAIL_VERIFICATION_SENT,
    EMAIL_VERIFIED,
    EXTRACTION_REQUESTED,
    MODERATION_CASE_CREATED,
    MODERATION_CASE_APPROVED,
    MODERATION_CASE_REJECTED,
    MODERATION_CASE_AUTO_BLOCKED,
    USER_MESSAGE_CREATED,
    USER_MESSAGE_UPDATED,
    USER_MESSAGE_DELETED,
    USER_MESSAGE_PROCESSED,
    SIGNAL_ENGINE_EXECUTED
}
